version: '3.0'
services:
  server:
    image: flesnjakovic/favourite-number-server:stable
    depends_on: 
      - redis
    links:
      - redis
    ports:
      - "8080:8080"
  worker:
    image: flesnjakovic/favourite-number-worker:stable
    depends_on: 
      - redis
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    
