version: '3.0'
services:
  server:
    build: ./server
    depends_on: 
      - redis
    links:
      - redis
    ports:
      - "8080:8080"
  worker:
    build: ./worker
    depends_on: 
      - redis
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    
